// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.jsx";
import * as $_app from "./routes/_app.jsx";
import * as $about from "./routes/about.jsx";
import * as $api_contact from "./routes/api/contact.js";
import * as $blog from "./routes/blog.jsx";
import * as $contact from "./routes/contact.jsx";
import * as $index from "./routes/index.jsx";
import * as $products from "./routes/products.jsx";
import * as $testimonials from "./routes/testimonials.jsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.jsx": $_404,
    "./routes/_app.jsx": $_app,
    "./routes/about.jsx": $about,
    "./routes/api/contact.js": $api_contact,
    "./routes/blog.jsx": $blog,
    "./routes/contact.jsx": $contact,
    "./routes/index.jsx": $index,
    "./routes/products.jsx": $products,
    "./routes/testimonials.jsx": $testimonials,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
